### ISSUE TITLE
`plistp` undefined

### ISSUE THREAD

**Issue by CGenie** [ahyatt/triples#1]
Hello,

I'm just trying out the sample from video https://toobnix.org/w/a26FMpRuCKmn4YZU4ysdrd.

I have this code:
```elisp
  (use-package triples)
  (let ((db (triples-connect "~/.emacs.bookmarks.db")))
    (triples-add-schema db
                        'bookmark
                        '(file :base/unique t :base/type string)
                        '(annotation :base/unique t :base/type string))
    (triples-add-schema db
                        'named
                        '(name :base/unique t :base/type string)))
```
However, when I execute the `let` statement, I get this error:
```
Debugger entered--Lisp error: (void-function plistp)
  plistp(nil)
  triples-db-insert(#<emacsql-sqlite-connection emacsql-sqlite-connection-155c1069fb94> bookmark base/type schema nil)
```

**Comment by CGenie** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Type-Predicates.html it seems `plistp` is not in the built-in predicates list. Unless you meant some 3rd party library that has that?

**Comment by ahyatt** [comment]
You're right, I need to fix this - `plistp` is built-in, but only in Emacs 29.
