### ISSUE TITLE
emacsql / built-in sqlite incompatibility with properties column

### ISSUE THREAD

**Issue by ahyatt** [ahyatt/triples#2]
This is demonstrated in https://github.com/ahyatt/ekg/issues/57.  It seems like the two backends write slightly different properties that are not compatible with each other.

**Comment by jayrajput** [comment]
I can see the old data fine with this fix. I am running triples from the develop branch. What about the new data accidentally created? I have two notes created with the id being string. I cannot see their text, nor call delete them? How do I see or delete those 2 notes. 

Thanks for the prompt fix.

**Comment by ahyatt** [comment]
Glad to hear this works.  I have a fix for your newly created notes, but I
need to test it out first.  Stay tuned.

**Comment by ahyatt** [comment]
I've checked in 668363c6e7399430fbd4f6e4297c6e55903d583a, which provides a new method to run to convert all string integers to integers.  I tried this out on my own database, and it seems to work, but please try it out yourself as well.  

If it works, I'll try it out on my work database, wait a week or so, then release the new version of the triples library.

**Comment by jayrajput** [comment]
works fine for me. I can see test2 tagged notes which were not visible before

```
(triples-upgrade-to-0.3 ekg-db)
```
