### ISSUE TITLE
Unresolved properties (:t t) after transit from emacsql to builtin sqlite

### ISSUE THREAD

**Issue by qingshuizheng** [ahyatt/triples#5]
Note: This topic is discussed in https://github.com/ahyatt/ekg/discussions/80#discussioncomment-6428656. I feel it being buried deep and off-topic there, so I branched it out here, hope you don't mind.

Recap:
I jumped around emacsql and builtin sqlite for experimental reasons several times. Due to the lack of mechanism 
 for converting emacsql- triples.properties `(:t t)` back to the builtin sqlite `()`, the db remains both versions of triples.properties, resulting the dup titles issues. Once the dups are removed and `(:t t)` is reset to `()`, the title back to normal.

![image](https://github.com/ahyatt/triples/assets/78839107/89651cd1-171a-4c6f-8d81-07f5519d209b)
  
Take your time making the new patch. 
Thanks for having helped me find out the issue.

**Comment by ahyatt** [comment]
Thanks for reminding me about this.  Please try out this latest commit in the `develop` branch and let me know if it works for you.

**Comment by qingshuizheng** [comment]
Works! My headache finally gone!
Thanks for the thoughtful fix.
