### ISSUE TITLE
Documentation: What should a subject be?

### ISSUE THREAD

**Issue by alphapapa** [ahyatt/triples#6]
Hi, looking at this library's docs again, it seems very interesting, but not being familiar with the triples concept, there's something I don't understand: What should a *subject* be?  In the examples, it's about a person named Alice, so the subject is the string `"alice"`.  But in a real application, what would it be?  What if there were other people named Alice?  In SQLish terms, what is the primary key supposed to be?  Some guidance on this matter would help me understand the library better.  :)

Also, since it's actually stored in SQL anyway, I think it would be helpful to have a paragraph or two describing why or how this is a better choice than using SQL directly.  Do the predicates/properties not map directly to columns in tables?  That is, is the idea that this allows more flexibility, without having to change the database schema?  If so, that's a big benefit, and it should probably be made more explicit.  :)

Thanks for your work.

**Comment by ahyatt** [comment]
Thanks for noting this.  It's a good call out, and so I took some time and wrote up some further documentation.  I hope this is helpful, if not let me know and I'll improve it.
